# Generated by Django 5.1.7 on 2025-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_cart_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('S', 'Shipped'), ('D', 'Delivered'), ('X', 'Cancelled')], default='P', max_length=1, null=True),
        ),
    ]
