# Generated by Django 5.1.7 on 2025-04-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_order_shipping_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
