# Generated by Django 5.1.7 on 2025-04-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
