# Generated by Django 5.1.7 on 2025-04-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
