# Generated by Django 5.1.7 on 2025-04-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_remove_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='exp_year',
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='last_four',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('CASH', 'cash'), ('CREDIT_CARD', 'credit_card')], default='credit_card', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='exp_date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CREDIT_CARD', 'credit_card'), ('PAYME_CARD', 'payme_card'), ('PAYPAL_CARD', 'paypal_card')], default='paypal_card', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shopping.order'),
        ),
    ]
